Repository AY2122S1-CS2103T-W11-2/tp, pull requests merged in 2021-11, with the labels that each got.

#224 Fix help message for setRoleReq
  src/main/java/seedu/address/logic/commands/SetRoleReqCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetRoleReqCommandParser.java
Labels: type.Bug, priority.High, severity.Medium

#232 Fixed editCommand schedule-wipe bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.High, severity.High

#233 Combine view command with find command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Task, priority.High, severity.High

#244 Clearer change command
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High

#234 Unclear markcommand ug
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Low

#249 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteShiftCommand.java
  src/main/java/seedu/address/logic/commands/SwapShiftCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, priority.Medium, severity.Medium

#239 Fixes bugs for SetDefaultShiftTimings and SetRoleReq Commands
  data/DefaultShiftTimings.txt
  data/RoleReq.txt
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultShiftTimingsCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetDefaultShiftTimingsCommandParser.java
  src/main/java/seedu/address/storage/DefaultShiftTimingsStorage.java
  src/main/java/seedu/address/storage/RoleReqStorage.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Bug, priority.High, severity.High

#237 Added date to dayCard
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/main/java/seedu/address/logic/commands/DeleteShiftCommand.java
  src/main/java/seedu/address/logic/commands/SchedulePeriodChangeCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultShiftTimingsCommand.java
  src/main/java/seedu/address/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/SchedulePeriodChangeCommandParser.java
  src/main/java/seedu/address/logic/parser/SetShiftTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/SwapShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewShiftCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RecurrencePeriod.java
  src/main/java/seedu/address/model/person/Period.java
  src/main/java/seedu/address/model/person/Shift.java
  src/main/java/seedu/address/storage/DefaultShiftTimingsStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedRecurrencePeriod.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/JsonAdaptedShift.java
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SlotCard.java
  src/main/java/seedu/address/ui/WeekShiftsPane.java
  src/main/resources/view/DayCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/commons/util/DateTimeUtilTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Enhancement, priority.Medium, severity.High

#256 Test Cases for SetRolesReq and SetDefaultShiftTimings Commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SetDefaultShiftTimingsCommand.java
  src/main/java/seedu/address/logic/commands/SetRoleReqCommand.java
  src/main/java/seedu/address/logic/commands/ViewShiftCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetDefaultShiftTimingsCommandParser.java
  src/main/java/seedu/address/logic/parser/SetRoleReqCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewShiftCommandParser.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/test/java/seedu/address/logic/commands/SetDefaultShiftTimingsCommandTest.java
  src/test/java/seedu/address/logic/commands/SetRoleReqCommandTest.java
  src/test/java/seedu/address/logic/parser/SetDefaultShiftTimingsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetRoleReqCommandParserTest.java
Labels: type.Bug, priority.High

#236 Storage testcases and bugs
  src/main/java/seedu/address/model/person/Shift.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/JsonAdaptedShift.java
  src/test/java/seedu/address/storage/JsonAdaptedPeriodTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRecurrencePeriodTest.java
  src/test/java/seedu/address/storage/JsonAdaptedShiftTest.java
Labels: type.Bug, priority.High, severity.High

#248 Modify setShiftTime
  src/main/java/seedu/address/logic/commands/SetShiftTimeCommand.java
  src/main/java/seedu/address/logic/parser/SetShiftTimeCommandParser.java
  src/test/java/seedu/address/logic/commands/SetShiftTimeCommandTest.java
  src/test/java/seedu/address/logic/parser/SetShiftTimeCommandParserTest.java
Labels: type.Enhancement, priority.Medium, severity.High

#247 Fix add shift command
  src/main/java/seedu/address/logic/commands/AddShiftCommand.java
  src/main/java/seedu/address/logic/parser/AddShiftCommandParser.java
  src/test/java/seedu/address/logic/parser/AddShiftCommandParserTest.java
Labels: type.Enhancement, priority.Medium, severity.High

#255 Add tests
  src/main/java/seedu/address/logic/commands/DeleteShiftCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteShiftCommandParserTest.java
Labels: type.Task, priority.High

#253 Add statistics test cases
  src/main/java/seedu/address/logic/commands/StaffIndividualStatisticsCommand.java
  src/test/java/seedu/address/logic/commands/StaffIndividualStatisticsCommandTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/stubs/model/FieldStub.java
Labels: type.Task, priority.High

#250 Add attendance related test cases
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/AddShiftCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveMarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetShiftTimeCommandParserTest.java
Labels: type.Task, priority.High, severity.Medium

#241 Update UG content related to addShift and SetShiftTime
  docs/UserGuide.md
Labels: priority.Medium

#258 Improve Storage implementation
  data/DefaultShiftTimings.txt
  data/RoleReq.txt
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultShiftTimingsCommand.java
  src/main/java/seedu/address/logic/commands/SetRoleReqCommand.java
  src/main/java/seedu/address/storage/DefaultShiftTimingsStorage.java
  src/main/java/seedu/address/storage/RoleReqStorage.java
Labels: type.Enhancement, priority.Medium

#254 Add recurrence period test cases
  src/main/java/seedu/address/model/RecurrencePeriod.java
  src/main/java/seedu/address/model/person/Period.java
  src/main/java/seedu/address/model/person/Shift.java
  src/test/java/seedu/address/model/person/PersonTestUtil.java
  src/test/java/seedu/address/model/person/RecurrencePeriodTest.java
  src/test/java/seedu/address/model/person/ShiftTest.java
Labels: type.Task, priority.High, severity.Medium

#263 Add summary format to UG
  docs/UserGuide.md
Labels: type.Bug, priority.High

#283 Update mark command details in UG
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High

#268 Fix mark problem
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug, priority.High, severity.High

#245 Add ppp for Gabau
  docs/team/gabau.md
Labels: type.Task, priority.High, severity.Medium

#301 GUI Update please LGTM me for UG pics c:
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/model/person/Period.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/SlotCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DayCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/SlotCard.fxml
Labels: type.Bug, priority.High, severity.High

#291 Address the inclusion of norole within add command
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High, severity.High

#308 Fixed unmark update
  src/main/java/seedu/address/ui/SlotCard.java
Labels: type.Bug, severity.High

#285 Removed address field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveMarkCommand.java
  src/main/java/seedu/address/logic/commands/StaffIndividualStatisticsCommand.java
  src/main/java/seedu/address/logic/commands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/StaffIndividualStatisticsCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/SetShiftTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/SwapShiftCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemoveMarkCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.VeryLow

#298 Delete set default shift timings
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultShiftTimingsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetDefaultShiftTimingsCommandParser.java
  src/main/java/seedu/address/storage/DefaultShiftTimingsStorage.java
  src/test/java/seedu/address/logic/commands/SetDefaultShiftTimingsCommandTest.java
  src/test/java/seedu/address/logic/parser/SetDefaultShiftTimingsCommandParserTest.java
Labels: type.Task, priority.High, severity.Low

#299 Various Bug Fixes and QOL Updates
  build.gradle
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveMarkCommand.java
  src/main/java/seedu/address/logic/commands/SetRoleReqCommand.java
  src/main/java/seedu/address/logic/commands/SetShiftTimeCommand.java
  src/main/java/seedu/address/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/SetShiftTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/StaffIndividualStatisticsCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Salary.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddShiftCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteShiftCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/SetShiftTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/SwapShiftCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/SalaryTest.java
Labels: type.Bug, priority.Medium

#314 Fix graphics color glitch
  src/main/java/seedu/address/ui/SlotCard.java
Labels: type.Bug, priority.Low, severity.Low

#259 Remove view schedule command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/Shift.java
Labels: type.Task, priority.High

#267 Fix role not filtering for newly added staff
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug, priority.High, severity.High

#279 Add period result to statistics command
  src/main/java/seedu/address/logic/commands/StaffIndividualStatisticsCommand.java
  src/main/java/seedu/address/logic/commands/StaffStatisticsCommand.java
Labels: type.Bug, priority.High, severity.High

#310 Fix norole lookups
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, priority.High, severity.High

#317 Change Prefix for Role-Requirements
  src/main/java/seedu/address/logic/commands/SetRoleReqCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SetRoleReqCommandParser.java
  src/test/java/seedu/address/logic/parser/SetRoleReqCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#316 Surya's PPP
  docs/team/tetrerox.md
Labels: type.Task, priority.High

#300 Make find command and search with fields and index
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug, priority.High, severity.High

#286 [WIP] Outong ppp
  docs/team/irvinghe000.md
Labels: type.Task, priority.High

#282 Modifications to viewShift command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewShiftCommand.java
  src/main/java/seedu/address/logic/parser/ViewShiftCommandParser.java
  src/main/java/seedu/address/model/person/Shift.java
Labels: type.Bug, priority.High, severity.High

#311 Change PPP gabau.md
  docs/team/gabau.md
Labels: type.Task, priority.High, severity.Low

#306 Change remove mark command
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveMarkCommand.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveMarkCommandTest.java
Labels: type.Bug, priority.High, severity.High

#287 Documentation update for 1.4 by Gab
  docs/DeveloperGuide.md
  docs/diagrams/AddShiftSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagramReference.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StoragePersonDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewShiftCommandExecutionSequenceDiagram.puml
  docs/diagrams/ViewShiftSequenceDiagram.puml
  docs/diagrams/WeekShiftsPaneClassDiagram.puml
  docs/images/AddShiftSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/StoragePersonDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/WeekShiftsPaneClassDiagram.png
  docs/images/findCommand/FindSequenceDiagram.png
  docs/images/viewShiftCommand/ViewShiftCommandExecutionSequenceDiagram.png
  docs/images/viewShiftCommand/ViewShiftSequenceDiagram.png
  docs/sample/addShift.json
  docs/sample/deleteAlex.json
  docs/sample/empty.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/SlotCard.java
Labels: type.Task, priority.High, severity.High

#313 Update DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#318 Message spacing issues
  src/main/java/seedu/address/logic/commands/SetShiftTimeCommand.java
  src/main/java/seedu/address/logic/commands/StaffIndividualStatisticsCommand.java
Labels: type.Bug, priority.Medium, severity.Medium

#315 Schedule GUI staff font
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement, priority.Low, severity.Low

#305 Alignment and sorting lists
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Enhancement, type.Bug, priority.Medium, severity.Low

#322 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/MarkActivityDiagram.puml
  docs/diagrams/gabau/MarkSequenceDiagram.puml
  docs/diagrams/gabau/PeriodUnionActivityDiagram.puml
  docs/images/MarkActivityDiagram.png
  docs/images/MarkSequenceDiagram.png
  docs/images/PeriodUnionActivityDiagram.png
Labels: type.Task, priority.High, severity.High

#324 Update dg Outong
  docs/DeveloperGuide.md
  docs/diagrams/AddShiftActivityDiagram.puml
  docs/diagrams/ViewShiftActivityDiagram.puml
  docs/images/AddShiftActivityDiagram.png
  docs/images/ViewShiftActivityDiagram.png
  docs/team/irvinghe000.md
Labels: type.Task, priority.Medium, severity.Medium

#326 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/team/tetrerox.md
Labels: type.Task, priority.High

#330 Improve User Guide
  docs/UserGuide.md
Labels: priority.High, severity.Medium

#331 Add nostatus to table
  docs/UserGuide.md
Labels: type.Bug, priority.High
