Repository AY2122S1-CS2103T-W11-2/tp, pull requests merged in 2021-10, with the labels that each got.

#35 Surya's DevGuide part
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#37 Add new classes related to staff's schedule.
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/Shift.java
  src/main/java/seedu/address/model/person/Slot.java
  src/main/java/seedu/address/model/person/exceptions/InvalidTimeException.java
  src/main/java/seedu/address/model/person/exceptions/OverlapTaskException.java
Labels: priority.High

#47 Add view command
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Field.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonContainsFieldsPredicate.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/stubs/model/ModelStub.java
Labels: type.Task, priority.High, hacktoberfest-accepted

#64 Adding Staff fields
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/Shift.java
  src/main/java/seedu/address/model/person/Slot.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/model/person/SalaryTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/model/person/StatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: hacktoberfest-accepted

#74 Update app icon and window title
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/staffd_icon.jpg
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Low, hacktoberfest-accepted

#71 Updating the GUI of our main window
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, priority.Medium, hacktoberfest-accepted

#73 Add addShift functionality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddShiftCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/Shift.java
  src/main/java/seedu/address/model/person/Slot.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateShiftException.java
  src/main/java/seedu/address/model/person/exceptions/InvalidTimeException.java
  src/main/java/seedu/address/model/person/exceptions/OverlapTaskException.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/stubs/model/ModelStub.java
Labels: type.Story, priority.High

#69 Delete staff details
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Story, priority.High, hacktoberfest-accepted

#87 Fix viewSchedule help message
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewScheduleCommandParser.java
Labels: type.Bug, priority.High, severity.High

#89 FIXED ADDCOMAND PROMPT
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, severity.High

#88 Multiple roles
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonContainsFieldsPredicate.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium, severity.High, hacktoberfest-accepted

#91 Improve PersonCard to GridView
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Enhancement, priority.Low, severity.VeryLow

#107 PersonBuilder schedule
  src/main/java/seedu/address/model/person/Schedule.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High, severity.Low

#102 FindScheduleCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveMarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ViewShiftCommand.java
  src/main/java/seedu/address/logic/parser/AddShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteShiftCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewShiftCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/Shift.java
  src/main/java/seedu/address/model/person/Slot.java
  src/main/java/seedu/address/model/person/predicates/PersonContainsFieldsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonIsWorkingPredicate.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveMarkCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewShiftCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewShiftCommandParserTest.java
Labels: type.Task, priority.High, severity.High

#187 Fixed salary parsing and error message
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/person/PeriodTest.java
  src/test/java/seedu/address/model/person/SalaryTest.java
Labels: type.Bug, severity.High

#225 Fix mark command tag
  docs/UserGuide.md
Labels: type.Task, type.Bug, priority.High

#226 Fixed personCard alignment issues
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Medium, severity.VeryLow
